language: node_js
node_js:
  "lts/*"
branches:
  only:
    - master
# before_script:
#   - npm install -g firebase-tools
# script:
#   - CI=false npm run build
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
